apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: pycbc-live
spec:
  runPolicy:
    cleanPodPolicy: None
  sshAuthMountPath: /home/mpi-user/.ssh
  runLauncherAsWorker: true
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: launcher
              image: olivergra/pycbc-live:k8s
              imagePullPolicy: Always
              env:
                - name: MPI_NP
                  value: "3"
                - name: MPI_HOST_ARGS
                  value: "--hostfile /etc/mpi/hostfile"
                - name: MPI_EXTRA_FLAGS
                  value: "--tag-output --timestamp-output --display-map --report-bindings"
                - name: LAL_DATA_PATH
                  value: /workspace/SEOBNRv4ROM
                - name: REQUESTS_CA_BUNDLE
                  value: /etc/gracedb-proxy-tls/tls.crt
              volumeMounts:
                - name: shared-workspace
                  mountPath: /workspace/tmp
                - name: gracedb-proxy-tls
                  mountPath: /etc/gracedb-proxy-tls
                  readOnly: true
              args:
                - /workspace/run.sh
          volumes:
            - name: shared-workspace
              persistentVolumeClaim:
                claimName: input-data
            - name: gracedb-proxy-tls
              secret:
                secretName: gracedb-proxy-tls
    Worker:
      replicas: 2
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: worker
              image: olivergra/pycbc-live:k8s
              imagePullPolicy: Always
              env:
                - name: LAL_DATA_PATH
                  value: /workspace/SEOBNRv4ROM
              volumeMounts:
                - name: shared-workspace
                  mountPath: /workspace/tmp
          volumes:
            - name: shared-workspace
              persistentVolumeClaim:
                claimName: input-data
