apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: o4-full-bandwidth-config
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: o4-full-bandwidth-output
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
